### ISSUE TITLE
Problem reacting to message

### ISSUE THREAD

**Issue by jdkDollaR** [WebTheDev/TicketBot#18]
Hello, I have a problem with the code! I can start the BOT and everything else, however, when the user reacts to the open ticket message, it gives me this error message. How could I resolve this? Sorry, my broken English is not my native language and I don't know much about Python either. I eagerly await a response.

```
ERROR    discord.ui.view Ignoring exception in view <TicketCreation timeout=None children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Create a new ticket' emoji=<PartialEmoji animated=False name='📩' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\Guilherme Oliveira\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ui\view.py", line 427, in _scheduled_task      
    await item.callback(interaction)
  File "C:\Users\Guilherme Oliveira\Desktop\TicketBot-4.3.6\create.py", line 285, in presscreate
    await interaction.response.send_message(embed=embed2, view=TicketCreationMenuUI(), ephemeral=True)
  File "C:\Users\Guilherme Oliveira\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\interactions.py", line 801, in send_message    
    await adapter.create_interaction_response(
  File "C:\Users\Guilherme Oliveira\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\webhook\async_.py", line 221, in request       
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.components.0.components.0.options.2: The specified option value is already used
```

**Comment by jdkDollaR** [comment]
After many attempts I managed to fix it, I got confused in putting some things in config.py. It's all OK
