### ISSUE TITLE
ImportError: cannot import name 'AppCommandOptionType' from 'discord.enums' 

### ISSUE THREAD

**Issue by Zertye** [WebTheDev/TicketBot#29]
![image_2024-11-02_110211158](https://github.com/user-attachments/assets/5d8e6643-2d9e-4aca-9fc0-b5475d6032d6)

**Comment by Zertye** [comment]
2024-11-02 12:14:34 ERROR    discord.ui.view Ignoring exception in view <embedButtons timeout=None children=2> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='Options' emoji=<PartialEmoji animated=False name='⚙️' id=None> row=None sku_id=None>
Traceback (most recent call last):
  File "C:\Users\nael\OneDrive\Desktop\parade 3\create.py", line 102, in ticketOptions
    acategoryc = (50 - (len(acategory.channels)))
                            ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'channels'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nael\OneDrive\Desktop\parade 3\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\nael\OneDrive\Desktop\parade 3\create.py", line 181, in ticketOptions
    await web.send(embed=embed)
          ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send'

**Comment by LadyVulcan** [comment]
I personally discovered this error when my bot was using a blend of both discord.py and py-cord. The py-cord version of discord.enums does not have AppCommandOptionType as an option, but discord.py does. Uninstalling py-cord and reinstalling discord.py helped me move on to a whole new set of errors.
